name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          sudo mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          sudo touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOST }}" &> /home/runner/.ssh/known_hosts
          sudo chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key rahul@34.93.139.231 -t "cd Deploy-Monorepo-Through-CI-CD/ && git pull origin main && export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games && sudo npm install -g pnpm && sudo pnpm install && sudo pnpm run build && sudo pnpm exec turbo run build --force -- --update-env && pm2 restart fe-sever && pm2 restart http-sever && pm2 restart ws-sever"